---
driver:
  name: vagrant
  provider: vmware_fusion

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5
    driver_config:
      network:
        - ["private_network", { ip: "192.168.22.22" }]

suites:
  - name: default
    run_list:
      - recipe[apache::default]
    attributes:
      motd:
        company: Chef
      apache:
        sites:
          ponies:
            port: 8082
