Style/AlignParameters:
  Enabled: false

Style/Encoding:
  Enabled: false

Metrics/LineLength:
  Max: 200

StringLiterals:
  Enabled: false

# Style/AlignParameters:
#   EnforcedStyle: with_fixed_indentation

# Style/TrailingComma:
#   EnforcedStyleForMultiline: comma

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

AllCops:
  Exclude:
    - "Vagrantfile"
